start_block : JUKEBOX
finish_block : NOTE_BLOCK

# %1$s = プレイヤー名 , %2$s = アスレ名 , %3$s = Time
start_message : ">>> %2$s§r 計測開始!"
finish_message : ">>> §n%1$s§r が、%2$s§r をクリアしました！ [%3$s]"

# タイムのホバー
show_ta_detail : false